// Die eigentliche Schicksalsdatenbank des Schicksalswürfels – bewusst getrennt von der
// Auswahl-Engine (fate-engine.ts) und der UI, damit hier jederzeit gefahrlos neue
// Einträge ergänzt werden können. Schweregrad reicht von "leicht" bis "extrem", nie belanglos.
// Übernatürliches ist ausschließlich Vampiren und Werwölfen vorbehalten.
import type { Fate, FateCategory, FateRoleRequirement, FateSeverity } from "@/lib/fate-types";

// Schicksal ohne Zusatz-Charaktere.
function s(
  id: number,
  category: FateCategory,
  severity: FateSeverity,
  text: string,
  opts: { char1?: FateRoleRequirement; tags?: string[] } = {},
): Fate {
  return { id, category, severity, minTargets: 0, maxTargets: 0, text, char1: opts.char1, tags: opts.tags };
}

// Schicksal mit genau einem möglichen Zusatz-Charakter (character2).
function t(
  id: number,
  category: FateCategory,
  severity: FateSeverity,
  text: string,
  opts: { optional?: boolean; soloText?: string; role?: FateRoleRequirement; char1?: FateRoleRequirement; tags?: string[] } = {},
): Fate {
  return {
    id,
    category,
    severity,
    minTargets: opts.optional ? 0 : 1,
    maxTargets: 1,
    text,
    soloText: opts.soloText,
    roles: [opts.role ?? {}],
    char1: opts.char1,
    tags: opts.tags,
  };
}

// Schicksal mit zwei zwingenden Zusatz-Charakteren (character2 und character3).
function t2(
  id: number,
  category: FateCategory,
  severity: FateSeverity,
  text: string,
  opts: { role2?: FateRoleRequirement; role3?: FateRoleRequirement; char1?: FateRoleRequirement; tags?: string[] } = {},
): Fate {
  return {
    id,
    category,
    severity,
    minTargets: 2,
    maxTargets: 2,
    text,
    roles: [opts.role2 ?? {}, opts.role3 ?? {}],
    char1: opts.char1,
    tags: opts.tags,
  };
}

const w = { gender: "maennlich" as const };
const f = { gender: "weiblich" as const };
const vamp: FateRoleRequirement = { species: ["vampir"] };
const wolf: FateRoleRequirement = { species: ["werwolf"] };

export const FATES: Fate[] = [
  // ---- Beziehung (1-28) ----
  t(1, "Beziehung", "schwer", "{character1} wird von {character2} betrogen.", { tags: ["Verrat"] }),
  t(2, "Beziehung", "mittel", "{character1} verliebt sich in {character2} – obwohl {character2} bereits vergeben ist.", { tags: ["Liebe"] }),
  t(3, "Beziehung", "schwer", "{character1} entdeckt, dass {character2} seit Monaten ein Geheimnis verschweigt.", { tags: ["Geheimnis", "Vertrauensbruch"] }),
  t(4, "Beziehung", "schwer", "{character1} wird von {character2} verlassen – ohne Vorwarnung.", { tags: ["Liebe", "Verlust"] }),
  t(5, "Beziehung", "mittel", "{character1} beginnt eine heimliche Beziehung mit {character2}.", { tags: ["Liebe", "Geheimnis"] }),
  t2(6, "Beziehung", "schwer", "{character1} entdeckt eine Affäre zwischen {character2} und {character3}.", { tags: ["Verrat", "Affäre"] }),
  t(7, "Beziehung", "schwer", "{character1} wird von {character2} öffentlich bloßgestellt.", { tags: ["Erniedrigung"] }),
  t(8, "Beziehung", "sehr schwer", "{character1} wird von {character2} erpresst – mit einem Geheimnis, das alles zerstören könnte.", { tags: ["Erpressung", "Geheimnis"] }),
  s(9, "Beziehung", "mittel", "{character1} muss sich zwischen zwei Menschen entscheiden, die {character1} beide etwas bedeuten.", { tags: ["Liebe", "Konflikt"] }),
  t(10, "Beziehung", "schwer", "{character1} entdeckt, dass die eigene Beziehung zu {character2} auf einer Lüge aufgebaut war.", { tags: ["Verrat", "Geheimnis"] }),
  t2(11, "Beziehung", "sehr schwer", "{character1} gerät zwischen {character2} und {character3} – beide kämpfen um {character1}.", { tags: ["Liebe", "Konflikt"] }),
  t(12, "Beziehung", "mittel", "{character1} merkt, dass die Gefühle für {character2} plötzlich alles andere überschatten.", { tags: ["Liebe"] }),
  t(13, "Beziehung", "schwer", "{character1} wird von {character2} vor die Wahl gestellt: alles oder nichts.", { tags: ["Konflikt", "Liebe"] }),
  s(14, "Beziehung", "mittel", "Ein lang gehütetes Gefühl bricht bei {character1} unkontrolliert hervor – mit Folgen, die sich nicht mehr verstecken lassen.", { tags: ["Liebe"] }),
  t(15, "Beziehung", "schwer", "{character1} findet heraus, dass {character2} eine zweite Beziehung führt.", { tags: ["Verrat", "Doppelleben"] }),
  t(16, "Beziehung", "sehr schwer", "{character1} wird von {character2} verraten – für jemand anderen.", { tags: ["Verrat"] }),
  s(17, "Beziehung", "schwer", "{character1} muss eine Beziehung beenden, die längst zu einer Last geworden ist.", { tags: ["Liebe", "Verlust"] }),
  t(18, "Beziehung", "mittel", "{character1} und {character2} geraten in einen Streit, der eine tiefere Kluft offenlegt.", { tags: ["Konflikt"] }),
  t(19, "Beziehung", "schwer", "{character1} entdeckt private Nachrichten von {character2}, die alles infrage stellen.", { tags: ["Vertrauensbruch", "Geheimnis"] }),
  t(20, "Beziehung", "sehr schwer", "{character1} wird von {character2} manipuliert – über Monate hinweg, ohne es zu bemerken.", { tags: ["Manipulation"] }),
  s(21, "Beziehung", "mittel", "{character1} erkennt, dass eine wichtige Beziehung nur noch aus Gewohnheit besteht.", { tags: ["Liebe"] }),
  t(22, "Beziehung", "schwer", "{character1} muss sich entscheiden: die Wahrheit sagen und {character2} verlieren, oder weiter schweigen.", { tags: ["Konflikt", "Geheimnis"] }),
  t(23, "Beziehung", "mittel", "{character1} bemerkt, dass {character2} sich in letzter Zeit auffällig distanziert.", { tags: ["Liebe", "Konflikt"] }),
  t(24, "Beziehung", "schwer", "{character1} wird Zeuge, wie {character2} mit jemand anderem intim wird.", { tags: ["Verrat", "Eifersucht"] }),
  s(25, "Beziehung", "sehr schwer", "{character1} verliert durch eine einzige Entscheidung die wichtigste Beziehung im Leben.", { tags: ["Verlust"] }),
  t(26, "Beziehung", "schwer", "{character1} erhält ein Ultimatum von {character2}: Vertrauen zurückgewinnen oder alles verlieren.", { tags: ["Vertrauensbruch", "Konflikt"] }),
  t(27, "Beziehung", "mittel", "{character1} entdeckt, dass {character2} heimlich Kontakt zu einer alten Beziehung hält.", { tags: ["Eifersucht", "Geheimnis"] }),
  t2(28, "Beziehung", "schwer", "{character1} erfährt, dass sich {character2} und {character3} heimlich hinter dem Rücken von {character1} abgesprochen haben.", { tags: ["Verrat", "Manipulation"] }),

  // ---- Familie / Schwangerschaft (29-46) ----
  t(29, "Familie", "sehr schwer", "{character1} wird schwanger von {character2}.", { optional: true, soloText: "{character1} wird schwanger.", role: w, char1: f, tags: ["Schwangerschaft"] }),
  t(30, "Familie", "sehr schwer", "{character1} erfährt, dass {character2} monatelang die eigene Schwangerschaft verheimlicht hat.", { role: f, tags: ["Schwangerschaft", "Geheimnis"] }),
  t(31, "Familie", "schwer", "{character1} erfährt, dass {character2} ein lange verborgenes Familienmitglied ist.", { tags: ["Familie", "Geheimnis"] }),
  s(32, "Familie", "schwer", "{character1} entdeckt ein schwerwiegendes Geheimnis in der eigenen Familie.", { tags: ["Familie", "Geheimnis"] }),
  t(33, "Familie", "sehr schwer", "{character1} erfährt, dass {character2} jahrelang über die eigene Herkunft gelogen hat.", { tags: ["Familie", "Identität", "Geheimnis"] }),
  s(34, "Familie", "schwer", "{character1} wird von der eigenen Familie verstoßen.", { tags: ["Familie", "Verlust"] }),
  t(35, "Familie", "sehr schwer", "{character1} erfährt, dass {character2} in Wahrheit ein leiblicher Elternteil ist.", { tags: ["Familie", "Identität"] }),
  s(36, "Familie", "mittel", "Ein alter Familienkonflikt bricht bei {character1} unerwartet wieder auf.", { tags: ["Familie", "Konflikt"] }),
  t(37, "Familie", "schwer", "{character1} entdeckt, dass {character2} ein Kind hat, von dem niemand wusste.", { tags: ["Familie", "Geheimnis"] }),
  s(38, "Familie", "sehr schwer", "{character1} verliert durch einen tragischen Vorfall ein Mitglied der eigenen Familie.", { tags: ["Familie", "Verlust"] }),
  t(39, "Familie", "schwer", "{character1} wird von {character2} vor eine Entscheidung gestellt, die die ganze Familie betrifft.", { tags: ["Familie", "Konflikt"] }),
  s(40, "Familie", "mittel", "{character1} erfährt, dass ein Erbe an unerwartete Bedingungen geknüpft ist.", { tags: ["Familie"] }),
  t(41, "Familie", "sehr schwer", "{character1} erfährt, dass {character2} nicht der leibliche Elternteil ist, für den {character2} sich all die Jahre ausgegeben hat.", { tags: ["Familie", "Identität", "Geheimnis"] }),
  s(42, "Familie", "schwer", "{character1} muss sich entscheiden, ob ein dunkles Familiengeheimnis ans Licht kommen darf.", { tags: ["Familie", "Geheimnis"] }),
  t(43, "Familie", "mittel", "{character1} und {character2} entdecken, dass sie enger verwandt sind, als beide dachten.", { tags: ["Familie", "Identität"] }),
  s(44, "Familie", "sehr schwer", "{character1} wird für ein Verbrechen verantwortlich gemacht, das jemand in der eigenen Familie begangen hat.", { tags: ["Familie", "Kriminalität"] }),
  t(45, "Familie", "schwer", "{character1} erfährt, dass {character2} für das Zerbrechen der eigenen Familie verantwortlich ist.", { tags: ["Familie", "Verrat"] }),
  s(46, "Familie", "schwer", "{character1} steht vor der Entscheidung, ein Familienmitglied für immer aus dem eigenen Leben zu streichen.", { tags: ["Familie", "Verlust"] }),

  // ---- Gefahr (47-74) ----
  t(47, "Gefahr", "sehr schwer", "{character1} wird von {character2} entführt.", { optional: true, soloText: "{character1} wird entführt.", tags: ["Entführung"] }),
  t(48, "Gefahr", "sehr schwer", "{character1} wird von {character2} verfolgt.", { optional: true, soloText: "{character1} wird verfolgt.", tags: ["Bedrohung"] }),
  t(49, "Gefahr", "schwer", "{character1} wird von {character2} überfallen.", { optional: true, soloText: "{character1} wird überfallen.", tags: ["Gewalt"] }),
  t(50, "Gefahr", "sehr schwer", "{character1} wird von {character2} erpresst.", { optional: true, soloText: "{character1} wird erpresst.", tags: ["Erpressung"] }),
  t(51, "Gefahr", "schwer", "{character1} wird von {character2} bedroht.", { optional: true, soloText: "{character1} wird bedroht.", tags: ["Bedrohung"] }),
  s(52, "Gefahr", "sehr schwer", "{character1} gerät in eine lebensgefährliche Situation.", { tags: ["Lebensgefahr"] }),
  t(53, "Gefahr", "sehr schwer", "{character1} wird von {character2} bei einem Autounfall schwer verletzt.", { optional: true, soloText: "{character1} wird bei einem Autounfall schwer verletzt.", tags: ["Unfall", "Verletzung"] }),
  s(54, "Gefahr", "sehr schwer", "{character1} wird angeschossen.", { tags: ["Gewalt", "Verletzung"] }),
  s(55, "Gefahr", "sehr schwer", "{character1} wird niedergestochen.", { tags: ["Gewalt", "Verletzung"] }),
  t(56, "Gefahr", "sehr schwer", "{character1} und {character2} haben gemeinsam einen schweren Autounfall.", { optional: true, soloText: "{character1} hat einen schweren Autounfall.", tags: ["Unfall", "Verletzung"] }),
  s(57, "Gefahr", "schwer", "{character1} wird Opfer eines Einbruchs, der alles verändert.", { tags: ["Kriminalität"] }),
  t(58, "Gefahr", "sehr schwer", "{character1} wird von {character2} als Druckmittel benutzt, um an jemand anderen heranzukommen.", { tags: ["Erpressung", "Manipulation"] }),
  s(59, "Gefahr", "schwer", "{character1} gerät in einen Hinterhalt, den niemand kommen sah.", { tags: ["Gewalt", "Bedrohung"] }),
  s(60, "Gefahr", "sehr schwer", "{character1} wird bei einem Brand schwer verletzt.", { tags: ["Unfall", "Verletzung"] }),
  t(61, "Gefahr", "sehr schwer", "{character1} wird von {character2} absichtlich in Lebensgefahr gebracht.", { tags: ["Gewalt", "Lebensgefahr"] }),
  s(62, "Gefahr", "schwer", "{character1} stürzt aus großer Höhe und trägt schwere Verletzungen davon.", { tags: ["Unfall", "Verletzung"] }),
  s(63, "Gefahr", "sehr schwer", "{character1} wird vergiftet.", { tags: ["Gewalt", "Lebensgefahr"] }),
  t2(64, "Gefahr", "sehr schwer", "{character1} wird als Geisel genommen, um {character2} zum Handeln zu zwingen – {character3} steht hilflos daneben.", { tags: ["Entführung", "Erpressung"] }),
  s(65, "Gefahr", "schwer", "{character1} überlebt nur knapp einen gezielten Anschlag.", { tags: ["Gewalt", "Lebensgefahr"] }),
  t(66, "Gefahr", "sehr schwer", "{character1} wird von {character2} aus einer brennenden Gefahr gerettet – um den Preis eines großen Geheimnisses.", { tags: ["Rettung", "Geheimnis"] }),
  s(67, "Gefahr", "schwer", "{character1} wird bei einer Explosion verletzt.", { tags: ["Unfall", "Verletzung"] }),
  t2(68, "Gefahr", "sehr schwer", "{character1} muss sich entscheiden, wen von beiden – {character2} oder {character3} – man zuerst aus der Gefahr rettet.", { tags: ["Konflikt", "Lebensgefahr"] }),
  s(69, "Gefahr", "schwer", "{character1} wird in ein gefährliches Gebiet gelockt, ohne die wahren Absichten dahinter zu kennen.", { tags: ["Manipulation", "Bedrohung"] }),
  t(70, "Gefahr", "sehr schwer", "{character1} wird von {character2} in eine Falle gelockt.", { tags: ["Manipulation", "Bedrohung"] }),
  s(71, "Gefahr", "schwer", "{character1} entkommt nur knapp einem Entführungsversuch.", { tags: ["Entführung"] }),
  s(72, "Gefahr", "sehr schwer", "{character1} wird schwer misshandelt und muss sich langsam zurückkämpfen.", { tags: ["Gewalt"] }),
  t(73, "Gefahr", "schwer", "{character1} wird von {character2} in einen gefährlichen Plan hineingezogen, ohne vorher gefragt zu werden.", { tags: ["Manipulation", "Bedrohung"] }),
  s(74, "Gefahr", "sehr schwer", "{character1} überlebt einen Mordanschlag nur knapp.", { tags: ["Mord", "Lebensgefahr"] }),

  // ---- Kriminalität (75-92) ----
  s(75, "Kriminalität", "sehr schwer", "{character1} wird eines schweren Verbrechens beschuldigt, das man nicht begangen hat.", { tags: ["Kriminalität"] }),
  s(76, "Kriminalität", "schwer", "{character1} wird verhaftet.", { tags: ["Kriminalität", "Gefängnis"] }),
  t(77, "Kriminalität", "sehr schwer", "{character1} wird von {character2} erpresst, um ein Verbrechen zu vertuschen.", { tags: ["Erpressung", "Kriminalität"] }),
  s(78, "Kriminalität", "schwer", "{character1} wird Zeuge eines schweren Verbrechens.", { tags: ["Kriminalität"] }),
  t(79, "Kriminalität", "sehr schwer", "{character1} wird von {character2} in ein Verbrechen hineingezogen.", { tags: ["Kriminalität", "Manipulation"] }),
  t(80, "Kriminalität", "sehr schwer", "{character1} wird von {character2} verraten – an die Polizei.", { tags: ["Verrat", "Kriminalität"] }),
  s(81, "Kriminalität", "schwer", "{character1} findet Beweise für ein Verbrechen, das jemand aus dem engsten Umfeld begangen hat.", { tags: ["Kriminalität", "Geheimnis"] }),
  t(82, "Kriminalität", "sehr schwer", "{character1} deckt auf, dass {character2} in ein Netzwerk organisierter Kriminalität verstrickt ist.", { tags: ["Kriminalität", "Doppelleben"] }),
  s(83, "Kriminalität", "schwer", "{character1} wird für ein Verbrechen, das man nicht begangen hat, öffentlich verdächtigt.", { tags: ["Kriminalität", "Erniedrigung"] }),
  t(84, "Kriminalität", "sehr schwer", "{character1} wird von {character2} gezwungen, über ein Verbrechen zu schweigen.", { tags: ["Erpressung", "Kriminalität"] }),
  s(85, "Kriminalität", "schwer", "{character1} gerät ins Visier einer Ermittlung.", { tags: ["Kriminalität"] }),
  t2(86, "Kriminalität", "sehr schwer", "{character1} entdeckt, dass {character2} und {character3} gemeinsam ein schweres Verbrechen begangen haben.", { tags: ["Kriminalität", "Geheimnis"] }),
  s(87, "Kriminalität", "sehr schwer", "{character1} wird entführt und als Druckmittel für ein Lösegeld benutzt.", { tags: ["Entführung", "Erpressung"] }),
  t(88, "Kriminalität", "schwer", "{character1} wird von {character2} bestohlen – um etwas, das nicht zu ersetzen ist.", { tags: ["Kriminalität", "Verlust"] }),
  s(89, "Kriminalität", "sehr schwer", "{character1} gerät zwischen die Fronten einer kriminellen Auseinandersetzung.", { tags: ["Kriminalität", "Bedrohung"] }),
  t(90, "Kriminalität", "sehr schwer", "{character1} wird von {character2} gezwungen, bei einem Verbrechen mitzumachen.", { tags: ["Erpressung", "Kriminalität"] }),
  s(91, "Kriminalität", "schwer", "{character1} wird Opfer eines gezielten Betrugs, der alles Ersparte kostet.", { tags: ["Kriminalität", "Verlust"] }),
  t(92, "Kriminalität", "sehr schwer", "{character1} findet heraus, dass {character2} seit Jahren ein Doppelleben als Kriminelle:r führt.", { tags: ["Kriminalität", "Doppelleben"] }),

  // ---- Vergangenheit / Geheimnisse (93-110) ----
  s(93, "Vergangenheit", "schwer", "Ein schweres Geheimnis von {character1} kommt ans Licht.", { tags: ["Geheimnis"] }),
  t(94, "Vergangenheit", "schwer", "{character1} wird mit einer Person aus der eigenen Vergangenheit konfrontiert: {character2}.", { tags: ["Vergangenheit"] }),
  s(95, "Vergangenheit", "sehr schwer", "{character1} erfährt eine schockierende Wahrheit über die eigene Herkunft.", { tags: ["Identität", "Vergangenheit"] }),
  t(96, "Vergangenheit", "schwer", "{character1} entdeckt, dass {character2} seit langer Zeit lügt.", { tags: ["Verrat", "Geheimnis"] }),
  s(97, "Vergangenheit", "schwer", "{character1} wird mit einer folgenschweren Entscheidung aus der eigenen Vergangenheit konfrontiert.", { tags: ["Vergangenheit"] }),
  t(98, "Vergangenheit", "sehr schwer", "{character1} entdeckt, dass {character2} ein dunkles Geheimnis über die eigene Person kennt.", { tags: ["Geheimnis", "Erpressung"] }),
  s(99, "Vergangenheit", "schwer", "Eine alte Wunde bei {character1} bricht durch einen Zufall wieder auf.", { tags: ["Trauma", "Vergangenheit"] }),
  t(100, "Vergangenheit", "sehr schwer", "{character1} erfährt, dass {character2} eine entscheidende Rolle in einem alten Trauma gespielt hat.", { tags: ["Trauma", "Vergangenheit"] }),
  s(101, "Vergangenheit", "mittel", "{character1} muss sich einer Entscheidung stellen, die jahrelang verdrängt wurde.", { tags: ["Vergangenheit"] }),
  t(102, "Vergangenheit", "schwer", "{character1} entdeckt Beweise dafür, dass {character2} nie die Wahrheit über die gemeinsame Geschichte gesagt hat.", { tags: ["Verrat", "Geheimnis"] }),
  s(103, "Vergangenheit", "sehr schwer", "{character1} erkennt, dass ein zentrales Erinnerungsstück der eigenen Vergangenheit eine Lüge war.", { tags: ["Identität", "Vergangenheit"] }),
  t(104, "Vergangenheit", "schwer", "{character1} wird von {character2} mit einem Versprechen aus der Vergangenheit konfrontiert, das nie eingelöst wurde.", { tags: ["Vertrauensbruch", "Vergangenheit"] }),
  s(105, "Vergangenheit", "sehr schwer", "{character1} erfährt, dass ein einschneidendes Ereignis der eigenen Kindheit ganz anders ablief als erinnert.", { tags: ["Trauma", "Vergangenheit"] }),
  t(106, "Vergangenheit", "sehr schwer", "{character1} entdeckt, dass {character2} für ein einschneidendes Unglück in der eigenen Vergangenheit verantwortlich ist.", { tags: ["Vergangenheit", "Verrat"] }),
  s(107, "Vergangenheit", "schwer", "{character1} muss sich einer Person aus der Vergangenheit stellen, die man für immer verloren glaubte.", { tags: ["Vergangenheit"] }),
  t(108, "Vergangenheit", "sehr schwer", "{character1} erfährt von {character2}, dass die eigene Identität nicht die ist, für die man sie hielt.", { tags: ["Identität", "Geheimnis"] }),
  s(109, "Vergangenheit", "schwer", "{character1} erhält einen Brief aus der Vergangenheit, der alles infrage stellt.", { tags: ["Vergangenheit", "Geheimnis"] }),
  t(110, "Vergangenheit", "sehr schwer", "{character1} entdeckt, dass {character2} seit Jahren Teil eines Geheimnisses ist, das die eigene Vergangenheit betrifft.", { tags: ["Geheimnis", "Vergangenheit"] }),

  // ---- Vampir (111-130) ----
  s(111, "Vampir", "sehr schwer", "{character1} wird von einem Vampir gebissen.", { tags: ["Vampire", "Verwandlung"] }),
  t(112, "Vampir", "sehr schwer", "{character1} wird von {character2}, einem Vampir, gebissen.", { role: vamp, tags: ["Vampire", "Verwandlung"] }),
  s(113, "Vampir", "sehr schwer", "{character1} wird von einem Vampir entführt.", { tags: ["Vampire", "Entführung"] }),
  s(114, "Vampir", "sehr schwer", "{character1} wird gegen den eigenen Willen in einen Vampir verwandelt.", { tags: ["Vampire", "Verwandlung"] }),
  t(115, "Vampir", "sehr schwer", "{character1} entdeckt, dass {character2} in Wahrheit ein Vampir ist.", { role: vamp, tags: ["Vampire", "Geheimnis"] }),
  s(116, "Vampir", "sehr schwer", "{character1} wird zum Ziel eines Vampirs, der es auf mehr als nur Blut abgesehen hat.", { tags: ["Vampire", "Bedrohung"] }),
  t2(117, "Vampir", "sehr schwer", "{character1} gerät zwischen zwei rivalisierende Vampire: {character2} und {character3}.", { role2: vamp, role3: vamp, tags: ["Vampire", "Konflikt"] }),
  s(118, "Vampir", "sehr schwer", "{character1} wird bei einem Angriff eines Vampirs schwer verletzt.", { tags: ["Vampire", "Verletzung"] }),
  t(119, "Vampir", "sehr schwer", "{character1} wird von {character2} vor einem Vampirangriff gerettet – um einen hohen Preis.", { tags: ["Vampire", "Rettung"] }),
  s(120, "Vampir", "sehr schwer", "{character1} findet Spuren eines Vampirangriffs in der eigenen Nachbarschaft.", { tags: ["Vampire", "Bedrohung"] }),
  t(121, "Vampir", "sehr schwer", "{character1} wird von {character2} vor eine Wahl gestellt: sich dem Ruf des Vampirblutes zu ergeben oder dagegen anzukämpfen.", { role: vamp, tags: ["Vampire", "Verwandlung"] }),
  s(122, "Vampir", "schwer", "{character1} spürt zum ersten Mal die Folgen eines lange zurückliegenden Vampirbisses.", { tags: ["Vampire", "Verwandlung"] }),
  t(123, "Vampir", "sehr schwer", "{character1} wird von {character2} als Vampir enttarnt – vor allen.", { role: vamp, tags: ["Vampire", "Geheimnis"] }),
  s(124, "Vampir", "sehr schwer", "{character1} wird nachts von einem Vampir verfolgt.", { tags: ["Vampire", "Bedrohung"] }),
  t(125, "Vampir", "sehr schwer", "{character1} erfährt, dass {character2} seit Jahren ein Vampirdasein verheimlicht.", { role: vamp, tags: ["Vampire", "Geheimnis"] }),
  s(126, "Vampir", "sehr schwer", "{character1} wird in einen Konflikt zwischen verfeindeten Vampirclans hineingezogen.", { tags: ["Vampire", "Konflikt"] }),
  t(127, "Vampir", "sehr schwer", "{character1} wird von {character2} gebissen und muss nun mit den ersten Anzeichen der Verwandlung leben.", { role: vamp, char1: { species: ["mensch"] }, tags: ["Vampire", "Verwandlung"] }),
  s(128, "Vampir", "sehr schwer", "{character1} wird Ziel eines Vampirs, der eine alte Rechnung begleichen will.", { tags: ["Vampire", "Bedrohung"] }),
  t(129, "Vampir", "sehr schwer", "{character1} muss sich entscheiden, ob {character2} nach der Verwandlung in einen Vampir noch vertraut werden kann.", { role: vamp, tags: ["Vampire", "Vertrauensbruch"] }),
  s(130, "Vampir", "sehr schwer", "{character1} wird nach einem nächtlichen Angriff mit ersten Symptomen einer Vampirverwandlung konfrontiert.", { tags: ["Vampire", "Verwandlung"] }),

  // ---- Werwolf (131-150) ----
  s(131, "Werwolf", "sehr schwer", "{character1} wird von einem Werwolf gebissen.", { tags: ["Werwölfe", "Verwandlung"] }),
  t(132, "Werwolf", "sehr schwer", "{character1} wird von {character2}, einem Werwolf, gebissen.", { role: wolf, tags: ["Werwölfe", "Verwandlung"] }),
  s(133, "Werwolf", "sehr schwer", "{character1} wird von einem Werwolf angegriffen.", { tags: ["Werwölfe", "Gewalt"] }),
  s(134, "Werwolf", "sehr schwer", "{character1} verwandelt sich zum ersten Mal in einen Werwolf.", { tags: ["Werwölfe", "Verwandlung"] }),
  t(135, "Werwolf", "sehr schwer", "{character1} entdeckt, dass {character2} in Wahrheit ein Werwolf ist.", { role: wolf, tags: ["Werwölfe", "Geheimnis"] }),
  s(136, "Werwolf", "sehr schwer", "{character1} wird von einem Werwolf verfolgt.", { tags: ["Werwölfe", "Bedrohung"] }),
  t2(137, "Werwolf", "sehr schwer", "{character1} gerät zwischen zwei verfeindete Werwölfe: {character2} und {character3}.", { role2: wolf, role3: wolf, tags: ["Werwölfe", "Konflikt"] }),
  s(138, "Werwolf", "sehr schwer", "{character1} wird bei einem Werwolfangriff schwer verletzt.", { tags: ["Werwölfe", "Verletzung"] }),
  t(139, "Werwolf", "sehr schwer", "{character1} wird von {character2} vor einem Werwolfangriff gerettet – um einen hohen Preis.", { tags: ["Werwölfe", "Rettung"] }),
  s(140, "Werwolf", "sehr schwer", "{character1} findet Spuren eines Werwolfangriffs in der Nähe des eigenen Zuhauses.", { tags: ["Werwölfe", "Bedrohung"] }),
  t(141, "Werwolf", "sehr schwer", "{character1} wird von {character2} vor eine Wahl gestellt: das Rudel oder die eigene Menschlichkeit.", { role: wolf, tags: ["Werwölfe", "Konflikt"] }),
  s(142, "Werwolf", "schwer", "{character1} spürt zum ersten Mal die Folgen eines lange zurückliegenden Werwolfbisses.", { tags: ["Werwölfe", "Verwandlung"] }),
  t(143, "Werwolf", "sehr schwer", "{character1} wird von {character2} als Werwolf enttarnt – vor allen.", { role: wolf, tags: ["Werwölfe", "Geheimnis"] }),
  s(144, "Werwolf", "sehr schwer", "{character1} wird bei Vollmond von einem Werwolf gejagt.", { tags: ["Werwölfe", "Bedrohung"] }),
  t(145, "Werwolf", "sehr schwer", "{character1} erfährt, dass {character2} seit Jahren ein Werwolfdasein verheimlicht.", { role: wolf, tags: ["Werwölfe", "Geheimnis"] }),
  s(146, "Werwolf", "sehr schwer", "{character1} wird in einen Konflikt zwischen verfeindeten Rudeln hineingezogen.", { tags: ["Werwölfe", "Konflikt"] }),
  t(147, "Werwolf", "sehr schwer", "{character1} wird von {character2} gebissen und muss nun mit den ersten Anzeichen der Verwandlung leben.", { role: wolf, char1: { species: ["mensch"] }, tags: ["Werwölfe", "Verwandlung"] }),
  s(148, "Werwolf", "sehr schwer", "{character1} wird Ziel eines Werwolfs, der eine alte Rechnung begleichen will.", { tags: ["Werwölfe", "Bedrohung"] }),
  t(149, "Werwolf", "sehr schwer", "{character1} muss sich entscheiden, ob {character2} nach der ersten Verwandlung noch vertraut werden kann.", { role: wolf, tags: ["Werwölfe", "Vertrauensbruch"] }),
  s(150, "Werwolf", "sehr schwer", "{character1} wird nach einem nächtlichen Vorfall mit den ersten Symptomen einer Werwolfverwandlung konfrontiert.", { tags: ["Werwölfe", "Verwandlung"] }),

  // ---- Extrem (151-172) ----
  s(151, "Kriminalität", "extrem", "{character1} wird ermordet.", { tags: ["Mord"] }),
  s(152, "Gefahr", "extrem", "{character1} überlebt einen Mordanschlag nur mit bleibenden Schäden.", { tags: ["Mord", "Bleibende Schäden"] }),
  s(153, "Kriminalität", "extrem", "{character1} tötet einen Menschen – aus Notwehr oder im Affekt.", { tags: ["Mord"] }),
  t(154, "Kriminalität", "extrem", "{character1} wird des Mordes an {character2} beschuldigt.", { tags: ["Mord", "Kriminalität"] }),
  t(155, "Familie", "extrem", "{character1} verliert {character2} durch Mord.", { tags: ["Mord", "Verlust"] }),
  t(156, "Kriminalität", "extrem", "{character1} wird Zeuge, wie {character2} jemanden tötet.", { tags: ["Mord", "Trauma"] }),
  s(157, "Gefahr", "extrem", "{character1} verliert bei einem Angriff ein Körperteil.", { tags: ["Bleibende Schäden", "Gewalt"] }),
  s(158, "Gefahr", "extrem", "{character1} wird bei einem Anschlag dauerhaft entstellt.", { tags: ["Bleibende Schäden", "Gewalt"] }),
  s(159, "Gefahr", "extrem", "{character1} erblindet durch eine Gewalttat.", { tags: ["Bleibende Schäden", "Gewalt"] }),
  s(160, "Gefahr", "extrem", "{character1} wird querschnittsgelähmt.", { tags: ["Bleibende Schäden", "Gewalt"] }),
  s(161, "Gefahr", "extrem", "{character1} trägt von einem Vorfall eine Behinderung davon, die das Leben für immer verändert.", { tags: ["Bleibende Schäden"] }),
  s(162, "Vergangenheit", "extrem", "{character1} trägt von einem traumatischen Erlebnis eine Wunde davon, die nie ganz heilt.", { tags: ["Trauma", "Bleibende Schäden"] }),
  t(163, "Beziehung", "extrem", "{character1} verliert nach einem Verrat von {character2} für immer das Vertrauen in andere Menschen.", { optional: true, soloText: "{character1} verliert nach einem schweren Verrat für immer das Vertrauen in andere Menschen.", tags: ["Verrat", "Vertrauensbruch"] }),
  t(164, "Beziehung", "extrem", "{character1} zerbricht innerlich an dem, was {character2} angetan hat.", { tags: ["Trauma", "Bleibende Schäden"] }),
  s(165, "Gefahr", "extrem", "{character1} entwickelt nach einem Angriff eine tiefe, dauerhafte Angst.", { tags: ["Trauma", "Bleibende Schäden"] }),
  s(166, "Gefahr", "extrem", "{character1} wird Opfer eines sexuellen Übergriffs.", { tags: ["Sexualisierte Gewalt"] }),
  t(167, "Beziehung", "extrem", "{character1} wird von {character2} sexuell missbraucht.", { tags: ["Sexualisierte Gewalt", "Vertrauensbruch"] }),
  s(168, "Gefahr", "extrem", "{character1} wird bei einer Folter schwer und dauerhaft gezeichnet.", { tags: ["Gewalt", "Bleibende Schäden"] }),
  s(169, "Kriminalität", "extrem", "{character1} begeht in einer Verzweiflungstat ein schweres Verbrechen.", { tags: ["Kriminalität"] }),
  s(170, "Kriminalität", "extrem", "{character1} wird lebenslang für ein Verbrechen inhaftiert, das jemand anderes begangen hat.", { tags: ["Kriminalität", "Gefängnis"] }),
  s(171, "Vampir", "extrem", "{character1} wird von einem Vampir fast vollständig ausgeblutet und überlebt nur knapp.", { tags: ["Vampire", "Lebensgefahr"] }),
  s(172, "Werwolf", "extrem", "{character1} verliert bei einem Angriff eines Werwolfs dauerhaft die Kontrolle über einen Teil des eigenen Körpers.", { tags: ["Werwölfe", "Bleibende Schäden"] }),

  // ---- Leicht (173-204) ----
  t(173, "Beziehung", "leicht", "{character1} bemerkt, dass sich etwas zwischen {character1} und {character2} verändert hat.", { tags: ["Liebe"] }),
  t(174, "Beziehung", "leicht", "{character1} und {character2} geraten in ihren ersten ernsten Streit.", { tags: ["Konflikt"] }),
  t(175, "Beziehung", "leicht", "{character1} merkt, dass eine Freundschaft zu {character2} in etwas Romantisches kippt.", { tags: ["Liebe"] }),
  t(176, "Beziehung", "leicht", "{character1} entdeckt eine kleine, aber unangenehme Notlüge von {character2}.", { tags: ["Vertrauensbruch"] }),
  t(177, "Beziehung", "leicht", "{character1} erhält eine unerwartete, unangenehme Nachricht von {character2}.", { tags: ["Konflikt"] }),
  s(178, "Familie", "leicht", "{character1} gerät mit der eigenen Familie wegen einer wichtigen Entscheidung aneinander.", { tags: ["Familie", "Konflikt"] }),
  s(179, "Familie", "leicht", "{character1} erfährt ein kleines, aber unangenehmes Familiengeheimnis.", { tags: ["Familie", "Geheimnis"] }),
  s(180, "Vergangenheit", "leicht", "{character1} wird unerwartet an eine unangenehme Erinnerung erinnert.", { tags: ["Vergangenheit"] }),
  s(181, "Vergangenheit", "leicht", "{character1} trifft zufällig auf jemanden aus einem eigentlich abgeschlossenen Lebensabschnitt.", { tags: ["Vergangenheit"] }),
  s(182, "Gefahr", "leicht", "{character1} entkommt knapp einer unangenehmen, aber ungefährlichen Situation.", { tags: ["Bedrohung"] }),
  s(183, "Gefahr", "leicht", "{character1} wird kurzzeitig verfolgt, ohne dass etwas passiert.", { tags: ["Bedrohung"] }),
  s(184, "Gefahr", "leicht", "{character1} wird Zeuge eines kleineren Vorfalls, der nachdenklich macht.", { tags: ["Konflikt"] }),
  s(185, "Kriminalität", "leicht", "{character1} wird Opfer eines kleineren Diebstahls.", { tags: ["Kriminalität"] }),
  s(186, "Kriminalität", "leicht", "{character1} gerät unverschuldet in eine unangenehme Befragung.", { tags: ["Kriminalität"] }),
  t(187, "Vampir", "leicht", "{character1} spürt in der Nähe von {character2} ein unerklärliches Unbehagen – etwas stimmt nicht.", { tags: ["Übernatürliches"] }),
  s(188, "Werwolf", "leicht", "{character1} bemerkt seltsame Anzeichen, die auf etwas Übernatürliches in der Nähe hindeuten.", { tags: ["Übernatürliches"] }),
  t(189, "Beziehung", "leicht", "{character1} verliebt sich unerwartet in {character2}.", { tags: ["Liebe"] }),
  t(190, "Beziehung", "leicht", "{character1} bemerkt, dass {character2} mehr als nur freundschaftliches Interesse zeigt.", { tags: ["Liebe"] }),
  t(191, "Beziehung", "leicht", "{character1} wird von {character2} zu einem Date eingeladen – und weiß nicht, was das bedeutet.", { tags: ["Liebe"] }),
  t(192, "Beziehung", "leicht", "{character1} erwischt sich dabei, ständig an {character2} zu denken.", { tags: ["Liebe"] }),
  t(193, "Beziehung", "leicht", "{character1} muss sich eingestehen, dass die Gefühle für {character2} nicht rein platonisch sind.", { tags: ["Liebe"] }),
  t(194, "Beziehung", "leicht", "{character1} merkt, dass {character2} die Freundschaft für die eigenen Zwecke ausnutzt.", { tags: ["Manipulation"] }),
  t(195, "Beziehung", "leicht", "{character1} wird von {character2} dazu überredet, etwas zu tun, das gegen die eigenen Prinzipien geht.", { tags: ["Manipulation"] }),
  t(196, "Beziehung", "leicht", "{character1} entdeckt, dass {character2} kleine Notlügen benutzt, um die eigenen Ziele zu erreichen.", { tags: ["Manipulation", "Vertrauensbruch"] }),
  t(197, "Beziehung", "leicht", "{character1} wird von {character2} geschickt gegen eine andere Person ausgespielt.", { tags: ["Manipulation"] }),
  t(198, "Beziehung", "leicht", "{character1} verliert eine Wette gegen {character2} – mit unangenehmen Konsequenzen.", { tags: ["Wetten"] }),
  t(199, "Beziehung", "leicht", "{character1} lässt sich von {character2} auf eine riskante Mutprobe ein.", { tags: ["Wetten"] }),
  t(200, "Beziehung", "leicht", "{character1} muss wegen einer verlorenen Wette gegen {character2} ein peinliches Geheimnis preisgeben.", { tags: ["Wetten", "Erniedrigung"] }),
  t(201, "Beziehung", "leicht", "{character1} wird eifersüchtig, als {character2} auffällig viel Zeit mit jemand anderem verbringt.", { tags: ["Eifersucht"] }),
  t(202, "Beziehung", "leicht", "{character1} gerät mit {character2} in eine spürbare Rivalität.", { tags: ["Rivalität"] }),
  s(203, "Beziehung", "leicht", "{character1} erfährt, dass ein Gerücht über die eigene Person die Runde macht.", { tags: ["Gerüchte"] }),
  t(204, "Beziehung", "leicht", "{character1} findet heraus, dass {character2} hinter dem eigenen Rücken über die eigene Person geredet hat.", { tags: ["Gerüchte", "Vertrauensbruch"] }),

  // ---- Zusätzliche Dynamiken: aktive Rolle & Übernatürliches entdecken (205-214) ----
  s(205, "Vampir", "schwer", "{character1} erfährt, dass es Vampire wirklich gibt.", { tags: ["Vampire", "Übernatürliches"] }),
  s(206, "Vampir", "schwer", "{character1} findet Beweise dafür, dass Vampire mitten unter den Menschen leben.", { tags: ["Vampire", "Übernatürliches"] }),
  s(207, "Werwolf", "schwer", "{character1} erfährt, dass es Werwölfe wirklich gibt.", { tags: ["Werwölfe", "Übernatürliches"] }),
  s(208, "Werwolf", "schwer", "{character1} findet Beweise dafür, dass Werwölfe mitten unter den Menschen leben.", { tags: ["Werwölfe", "Übernatürliches"] }),
  t(209, "Kriminalität", "schwer", "{character1} erpresst {character2}.", { tags: ["Erpressung"] }),
  t(210, "Kriminalität", "sehr schwer", "{character1} erpresst {character2} mit einem gefährlichen Geheimnis.", { tags: ["Erpressung", "Geheimnis"] }),
  t(211, "Beziehung", "schwer", "{character1} manipuliert {character2}, um an das zu kommen, was gewollt wird.", { tags: ["Manipulation"] }),
  t(212, "Beziehung", "schwer", "{character1} verrät {character2} für den eigenen Vorteil.", { tags: ["Verrat"] }),
  t(213, "Gefahr", "schwer", "{character1} droht {character2} unverhohlen.", { tags: ["Bedrohung"] }),
  t(214, "Beziehung", "sehr schwer", "{character1} stellt {character2} vor eine unmögliche Wahl.", { tags: ["Manipulation", "Konflikt"] }),

  // ---- Kontrollverlust: Vampire & Werwölfe (215-226) ----
  s(215, "Vampir", "extrem", "{character1} verliert bei einem Blutrausch die Kontrolle und tötet eine unschuldige Person.", { tags: ["Vampire", "Kontrollverlust", "Mord"] }),
  s(216, "Vampir", "sehr schwer", "{character1} verliert bei einem Blutrausch die Kontrolle und verletzt eine unschuldige Person schwer.", { tags: ["Vampire", "Kontrollverlust", "Gewalt"] }),
  t(217, "Vampir", "extrem", "{character1} verliert die Kontrolle und tötet {character2} – einen nahen Verwandten.", { optional: true, soloText: "{character1} verliert die Kontrolle und tötet einen nahen Verwandten.", tags: ["Vampire", "Kontrollverlust", "Mord", "Familie"] }),
  t(218, "Vampir", "sehr schwer", "{character1} verliert die Kontrolle und verletzt {character2} schwer – einen nahen Verwandten.", { optional: true, soloText: "{character1} verliert die Kontrolle und verletzt einen nahen Verwandten schwer.", tags: ["Vampire", "Kontrollverlust", "Gewalt", "Familie"] }),
  t(219, "Vampir", "extrem", "{character1} verliert die Kontrolle und tötet {character2} – einen geliebten Menschen.", { optional: true, soloText: "{character1} verliert die Kontrolle und tötet einen geliebten Menschen.", tags: ["Vampire", "Kontrollverlust", "Mord", "Liebe"] }),
  t(220, "Vampir", "sehr schwer", "{character1} verliert die Kontrolle und verletzt {character2} schwer – einen geliebten Menschen.", { optional: true, soloText: "{character1} verliert die Kontrolle und verletzt einen geliebten Menschen schwer.", tags: ["Vampire", "Kontrollverlust", "Gewalt", "Liebe"] }),
  s(221, "Werwolf", "extrem", "{character1} verliert bei einer Verwandlung die Kontrolle und tötet eine unschuldige Person.", { tags: ["Werwölfe", "Kontrollverlust", "Mord"] }),
  s(222, "Werwolf", "sehr schwer", "{character1} verliert bei einer Verwandlung die Kontrolle und verletzt eine unschuldige Person schwer.", { tags: ["Werwölfe", "Kontrollverlust", "Gewalt"] }),
  t(223, "Werwolf", "extrem", "{character1} verliert die Kontrolle und tötet {character2} – einen nahen Verwandten.", { optional: true, soloText: "{character1} verliert die Kontrolle und tötet einen nahen Verwandten.", tags: ["Werwölfe", "Kontrollverlust", "Mord", "Familie"] }),
  t(224, "Werwolf", "sehr schwer", "{character1} verliert die Kontrolle und verletzt {character2} schwer – einen nahen Verwandten.", { optional: true, soloText: "{character1} verliert die Kontrolle und verletzt einen nahen Verwandten schwer.", tags: ["Werwölfe", "Kontrollverlust", "Gewalt", "Familie"] }),
  t(225, "Werwolf", "extrem", "{character1} verliert die Kontrolle und tötet {character2} – einen geliebten Menschen.", { optional: true, soloText: "{character1} verliert die Kontrolle und tötet einen geliebten Menschen.", tags: ["Werwölfe", "Kontrollverlust", "Mord", "Liebe"] }),
  t(226, "Werwolf", "sehr schwer", "{character1} verliert die Kontrolle und verletzt {character2} schwer – einen geliebten Menschen.", { optional: true, soloText: "{character1} verliert die Kontrolle und verletzt einen geliebten Menschen schwer.", tags: ["Werwölfe", "Kontrollverlust", "Gewalt", "Liebe"] }),
];
